# See https://github.com/pypa/python-manylinux-demo
# vim: set ts=8 sts=2 sw=2:
notifications:
  email: false

language: python
python: 3.6
os: linux

stages:
  - name: test
    if: (branch IN (master)) OR (tag =~ /^release-/)
  - name: deploy
    if: (type = push) AND (tag =~ /^release-/)

jobs:
  include:
    - name: "Run tests"
      before_script:
        - scripts/build-sdist.sh
      script:
        - scripts/run-tests.sh
    - stage: deploy
      name: "Build manylinux2014"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
      before_install:
        - docker pull $DOCKER_IMAGE
    - name: "Build manylinux2010"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
      before_install:
        - docker pull $DOCKER_IMAGE
    - name: "Build manylinux2010 (32-bit)"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
           PRE_CMD=linux32
           PLAT=manylinux2010_i686
      before_install:
        - docker pull $DOCKER_IMAGE

install:
  - scripts/fetch-md4c.sh md4c-lib

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/scripts/build-linux.sh
  - ls dist/

deploy:
  provider: pypi
  skip_cleanup: true
  # Workaround to keep dpl from running "python setup.py sdist" (setting to
  # empty string errors the build)
  distributions: "--version"
  username: "__token__"
  password:
    secure: "HBIZNf2wVDheWxbHpJxpMafVGfkmbUTJ1L2LqkZVxXwu0FTVCk5qaTSLcAqjpQN8HpZXQe1TE6osjfiy8qjuuQuNRAyzFpjLu9Kw7Vl571cYLe7cpYFdZeyDn0rYHP7gCYB4lNlw7b3ahlLl8UZ/2u26y4MZKx+0pqPgrxBZ3mjefcKwtf41CGayGh2YxB3dbJKDnYZGeXIml4Iq9aOK2GjH7sNaLB/QLDJcYtz1CSN+L7dU+qXRUcb209Tn/s1IQXhKz2PSqAxgUUdtfROTZT+41GORsJEGuM7VEJ/aZYGChyaTGh0iIwYslCpoW2ZuZjTFDfcpO0xd88R2YT4B6B3eoZGWRAO3hqGGtKEQBic8HpFbIdMeoPcb/2cxfqOuIFMnRvGE6tLKlgHHuSGzHN3u6hJWfwHw52jj4osBrzwRclKzERwkB/qXUbguTvoHsOyTt0YwsRFWbkmiuVdNXJ7JBbtszCtVqKcQNZZv/CnBQC6oX7VrfLY76eeeN4k6/8UcacYtvreM8mdkXiMOiKL8TDL+pqTF0cx0G6SKdrfOguueXb5pIUTUCSAgEwA1+65DGfdbjb/jpQ/PhJhiSx1FHcMFZc6LLLz3qtBQDtsL/IZp7W7gOXWcPuvX+3oLZ8OLjGg4weXTgNOdex3JDQfOQIDTzIf5n5m8UZfV9Jc="
  on:
    tags: true
    condition: $TRAVIS_TAG = release-*
  #DEBUG
  #server: https://test.pypi.org/legacy/
  #skip_existing: true
