# See https://github.com/pypa/python-manylinux-demo
# vim: set ts=8 sts=2 sw=2:
#TODO Add a testing stage, and then this becomes deployment stage
branches:
  only:
    - master

notifications:
  email: false

language: generic
os: linux

jobs:
  include:
    - name: "Build manylinux2014"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
      before_install:
        - docker pull $DOCKER_IMAGE
    - name: "Build manylinux2010"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
      before_install:
        - docker pull $DOCKER_IMAGE
    - name: "Build manylinux2010 (32-bit)"
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
           PRE_CMD=linux32
           PLAT=manylinux2010_i686
      before_install:
        - docker pull $DOCKER_IMAGE
    - name: "Build for macOS"
      os: osx
      #TODO
    - name: "Build for Windows"
      os: windows
      before_install:
        - choco install python3 --version=3.6
        - python3 -m pip install --upgrade pip setuptools wheel
      #TODO

install:
  - scripts/fetch-md4c.sh md4c-lib

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/scripts/build-wheels.sh
  - ls wheelhouse/

#deploy:
  #provider: pypi
  #username: "__token__"
  #password:
    #secure: "aq8Q5HuW5wv8DyTXIGeZHonJWlLBOnnT2CS7SFz0Dbb9xdTIihoJmASyqfwbdKicpzyt9snTtN0HL64O98+h3r8Bdsiu/QGOli2/oKmACPd+7+Kl0JnujaordDMhUxGZ3zz6W6RdL4/zuz2Gupb5P2aweVyf3rA65e2PBA+hsVj4JeX/XhrskMINh1qw5doYpUZ1ZOzi0bB1KGJoL3ArJsR8uj5bDoVwXIHolM68tGjtYAEGNVNdZLfRMudwn2H9bWYBBbdYBuRKiIrfFFrT9UV+ruxaM7+mA5K8EtG28cVyDxN1h6Xu1aoeWHMokZfZ4Ji7NtAAM/DWMfVqdTZc6jAis6FyWIqyABtkSfY+W+gi9d1UWfDnY2uYDtOw1coWUNlutcZycSZ9jz5TJWXkHs9Eck1CTIoCjXegvzQqmPjFJWFHnZSFiUk0RpkxBIjID18s56jjNePPeuJWxMfR5grf+/9EfFH2ASG/BsssB0yNvWtOPBrCr5Ofb0UWp5DBFdYMUKwKrypeN2KG5dgUIVKkX2Uv4QdmB+OX405a9tjMBp9ngFS5uXyxyLVqPCwtRgWTRgFhkUk8otuKhnTieGMYWwa6/QtwXDt+MYnrMjZ64uAqBO1eyPIfLit96vTtlxFo+ZqsNDpoAajeh3gV/G3PFeoMsJqUsIa8PiAlVNo="
  #on:
    #tags: true
  #TODO
