# vim: set ts=8 sts=2 sw=2:

name: Get MD4C version
description: Get the version of MD4C to link against
outputs:
  md4c-version:
    description: The MD4C version to link against
    value: ${{steps.get-version.outputs.md4c}}
  md4c-min:
    description: The oldest MD4C version to test against
    value: ${{steps.get-version.outputs.md4c-min}}
runs:
  using: composite
  steps:
    - id: get-version
      run: |
        import json
        with open('about.json') as f:
            about = json.load(f)
        min_version = about['md4c-version']['min']
        max_version = about['md4c-version']['max']
        print('::set-output name=md4c::' + max_version)
        print('::set-output name=md4c-min::' + min_version)
      shell: python3
