# vim: set ts=8 sts=2 sw=2:

name: Get MD4C version
description: Get the version of MD4C to link against
outputs:
  md4c-version:
    description: The MD4C version to link against
    value: ${{steps.get-version.outputs.md4c}}
  md4c-min:
    description: The oldest MD4C version to test against
    value: ${{steps.get-version.outputs.md4c-min}}
runs:
  using: composite
  steps:
    - id: get-version
      run: |
          python3 "$GITHUB_ACTION_PATH/get_version.py"
      shell: bash
