# GitHub Action for test suite
# vim: set ts=8 sts=2 sw=2:
name: test
on:
  push:
    branches:
      - dev
        #- github-actions
  pull_request:
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: md4c-version
        name: Get compatible MD4C version
        uses: ./.github/actions/md4c-version
      - name: Fetch MD4C
        uses: actions/checkout@v2
        with:
          repository: mity/md4c
          ref: release-${{steps.md4c-version.outputs.md4c-version}}
          path: md4c-lib
      - name: Build and install MD4C
        run: |
          mkdir md4c-lib/build
          cd md4c-lib/build
          cmake ..
          make
          sudo make install
      - name: Install Python packaging tools
        run: python3 -m pip install --upgrade pip setuptools wheel
      - name: Install PyMD4C with test dependencies
        run: python3 -m pip install .[test]
      - name: Check setup.py
        run: python3 setup.py check -m -s
      - name: Run flake8
        run: flake8 .
      #TODO Add actual tests

